import { TravelTemplate } from "../types";

export const TRAVEL_TEMPLATES: TravelTemplate[] = [
  // --- 여행 템플릿 ---
  {
    id: "jeju-3days",
    title: "제주도 3박 4일 감성 카페 & 해안도로 코스",
    categoryType: "travel",
    destination: "제주도",
    style: "감성 카페, 해안도로 드라이브, 바다 전망 맛집",
    icon: "🏝️",
    description: "애월 해안도로부터 구좌읍 세화 해변, 우도까지 에메랄드빛 바다와 신상 감성 카페를 정복하는 알찬 3박 4일",
    duration: "3박 4일",
    keywords: ["애월해안도로", "세화해변", "우도자전거투어", "제주흑돼지", "돌담카페"],
    tone: "친근하고 감성적인 ~해요체 (인스타그램 감성)",
  },
  {
    id: "tokyo-gourmet",
    title: "도쿄 2박 3일 미식 & 쇼핑 핫플 탐방기",
    categoryType: "travel",
    destination: "일본 도쿄",
    style: "식도락, 핫플레이스 쇼핑, 야경 감상",
    icon: "🗼",
    description: "시부야 스카이 전망대, 시부야 하라주쿠 빈티지 숍, 아키하바라, 오모테산도 디저트 카페와 긴자 라멘 투어",
    duration: "2박 3일",
    keywords: ["시부야스카이", "오모테산도카페", "신주쿠야경", "도쿄라멘맛집", "하라주쿠쇼핑"],
    tone: "솔직하고 생생한 리얼 후기 체",
  },
  {
    id: "barcelona-gaudi",
    title: "스페인 바르셀로나 가우디 건축 & 타파스 기행",
    categoryType: "travel",
    destination: "스페인 바르셀로나",
    style: "문화 예술, 건축 탐방, 스페인 와인 & 타파스",
    icon: "🏰",
    description: "사그라다 파밀리아 성당, 구엘 공원, 카사 바트요부터 람블라 거리의 바르셀로네타 해변과 타파스 투어까지",
    duration: "4박 5일",
    keywords: ["사그라다파밀리아", "구엘공원", "람블라거리", "바르셀로네타", "스페인타파스"],
    tone: "정보가 풍부한 유럽 전문가 가이드 어조",
  },
  {
    id: "kyoto-autumn",
    title: "교토 3박 4일 고즈넉한 전통 거리 & 힐링 료칸",
    categoryType: "travel",
    destination: "일본 교토",
    style: "전통 문화, 힐링 료칸, 말차 디저트",
    icon: "🍁",
    description: "청수사(키요미즈데라)와 아라시야마 대나무 숲, 가온 거리의 게이샤 거리, 온천 료칸 가이세키 요리 체험",
    duration: "3박 4일",
    keywords: ["아라시야마", "청수사", "기온거리", "료칸가이세키", "교토말차"],
    tone: "서정적이고 고즈넉한 감성 어조",
  },
  {
    id: "danang-family",
    title: "베트남 다낭&호이안 3박 5일 가성비 휴양 코스",
    categoryType: "travel",
    destination: "베트남 다낭/호이안",
    style: "가족 휴양, 해변 리조트, 야경 등불 거리",
    icon: "🥥",
    description: "미케 비치 해변 리조트, 바나힐 케이블카 & 골든브릿지, 호이안 올드타운 밤거리 등불 투어와 반미/쌀국수 맛집",
    duration: "3박 5일",
    keywords: ["미케비치", "바나힐골든브릿지", "호이안올드타운", "다낭야시장", "베트남쌀국수"],
    tone: "친절하고 가족 여행자용 세심한 가이드",
  },
  {
    id: "paris-romantic",
    title: "프랑스 파리 5박 6일 감성 스냅 & 루브르 박물관 코스",
    categoryType: "travel",
    destination: "프랑스 파리",
    style: "에펠탑 야경, 미술관 투어, 센강 크루즈, 베이커리 맛집",
    icon: "🥐",
    description: "에펠탑 샤오궁 스냅 스팟, 루브르 & 오르세 미술관, 센강 바토무슈 크루즈, 몽마르트르 언덕과 크루아상 맛집 투어",
    duration: "5박 6일",
    keywords: ["에펠탑야경", "루브르박물관", "센강크루즈", "몽마르트르", "파리크루아상"],
    tone: "로맨틱하고 감성 가득한 유럽 여행 에세이 어조",
  },

  // --- 생활정보 & 팁 템플릿 ---
  {
    id: "ac-electricity-save",
    title: "여름철 에어컨 전기요금 50% 절약하는 실전 꿀팁 7가지",
    categoryType: "life_info",
    destination: "에어컨 전기세 절약법",
    style: "절약 / 재테크 / 생활노하우",
    icon: "💡",
    description: "인버터형vs정속형 구분법부터 제습 모드의 오해, 서큘레이터 조합 및 에어컨 필터 청소 주기로 전기요금 폭탄 완벽 방지!",
    duration: "소요시간 5분 읽기",
    keywords: ["에어컨전기세절약", "누진세예방", "살림꿀팁", "자취생전기세", "에어컨필터청소"],
    tone: "친근하고 쉬운 생활전문가 블로그체",
  },
  {
    id: "fridge-organization",
    title: "자취생 필수! 10분 만에 끝내는 냉장고 정돈 & 냄새 제거 살림법",
    categoryType: "life_info",
    destination: "냉장고 정돈 및 냄새 제거",
    style: "청소 / 살림 / 자취가이드",
    icon: "🧹",
    description: "소주와 베이킹소다를 활용한 천연 탈취제 만들기, 식재료 보관 기한표, 서랍별 냉장/냉동 보관 법칙 총정리",
    duration: "실행 10분 완료",
    keywords: ["냉장고냄새제거", "자취생살림팁", "베이킹소다활용법", "냉장고정리", "식재료보관법"],
    tone: "위트있고 상쾌한 살림고수 리뷰체",
  },
  {
    id: "one-pan-pasta",
    title: "요알못도 성공하는 15분 초간단 원팬 알리오 올리오 파스타",
    categoryType: "life_info",
    destination: "초간단 원팬 파스타 레시피",
    style: "요리 / 레시피 / 자취 요리",
    icon: "🍳",
    description: "설거지거리 단 1개! 마늘과 올리브유, 페페론치노만으로 파스타 전문점 맛을 내는 황금 비율 원팬 요리 레시피",
    duration: "조리시간 15분",
    keywords: ["원팬파스타", "초간단자취요리", "알리오올리오", "10분레시피", "자취생저녁"],
    tone: "친절하고 친근한 집밥 요리 블로그체",
  },
  {
    id: "phone-battery-tips",
    title: "스마트폰 배터리 수명 2배 늘리고 빠르고 쾌적하게 쓰는 필수 설정",
    categoryType: "life_info",
    destination: "스마트폰 배터리 및 속도 설정",
    style: "디지털 / IT / 스마트폰 팁",
    icon: "📱",
    description: "아이폰 & 갤럭시 배터리 성능 저하 방지 모드, 백그라운드 앱 정리, 다크모드 설정으로 배터리 조기 방전 방지법",
    duration: "설정 3분 완료",
    keywords: ["스마트폰배터리절약", "아이폰꿀팁", "갤러시배터리", "IT테크팁", "스마트폰수명"],
    tone: "명확하고 전문적인 디바이스 가이드체",
  },
  {
    id: "youth-subsidy-2026",
    title: "2026년 청년 & 무주택 서민 필수 정부 지원금 신청 총정리",
    categoryType: "life_info",
    destination: "정부 지원금 및 정책 혜택",
    style: "정책 / 행정 / 서민지원",
    icon: "📑",
    description: "청년도약계좌, 청년 월세 지원금, 대중교통 K-패스 환급 제도 자격 요건과 복지로 사이트 신청 방법 step-by-step",
    duration: "신청 10분 완료",
    keywords: ["청년지원금", "정부혜택", "청년도약계좌", "K패스환급", "복지로신청"],
    tone: "상세하고 알기 쉬운 정보 전달 가이드체",
  },

  // --- 🍽️ 맛집 / 카페 템플릿 ---
  {
    id: "sungsu-bakery-cafe",
    title: "성수동 오픈런 신상 베이커리 & 감성 카페 투어 BEST 5",
    categoryType: "food",
    destination: "서울 성수동 핫플 카페 & 베이커리",
    style: "베이커리 카페, 인테리어 핫플, 인생샷 스팟",
    icon: "🥐",
    description: "웨이팅 필수 소금빵 맛집부터 통창 루프탑 뷰, 핸드드립 커피와 디저트 페어링까지 주말 성수 핫플 정복 코스",
    duration: "반나절 코스",
    keywords: ["성수동카페", "소금빵성지", "성수베이커리", "인생샷카페", "오픈런"],
    tone: "트렌디하고 감성적인 인스타그램 인플루언서 톤",
  },
  {
    id: "euljiro-nopo-food",
    title: "을지로·종로 힙지로 골목 줄 서는 찐노포 & 야장 맛집 로드",
    categoryType: "food",
    destination: "서울 을지로·종로 노포 & 야장 맛집",
    style: "노포 감성, 야장 맛집, 가성비 식도락",
    icon: "🍲",
    description: "레트로 감성 물씬 나는 냉삼 골목, 줄 서서 먹는 평양냉면, 시원한 생맥주와 노가리 야장까지 실패 없는 을지로 미식 가이드",
    duration: "저녁 식도락 투어",
    keywords: ["힙지로맛집", "을지로노포", "종로야장", "냉동삼겹살", "노가리골목"],
    tone: "솔직담백하고 생생한 리얼 미식 후기체",
  },
  {
    id: "yeonnam-dining-coffee",
    title: "연남동 골목 숨은 일식 다이닝 & 핸드드립 스페셜티 커피 탐방기",
    categoryType: "food",
    destination: "서울 연남동 감성 맛집 & 스페셜티 카페",
    style: "골목 감성 다이닝, 스페셜티 커피, 분위기 데이트",
    icon: "☕",
    description: "연트럴파크 골목 안쪽에 숨겨진 감성 일식 솥밥집과 앤틱한 분위기에서 즐기는 싱글오리진 핸드드립 커피 페어링",
    duration: "데이트 코스 4시간",
    keywords: ["연남동맛집", "핸드드립카페", "연트럴파크", "일식솥밥", "분위기데이트"],
    tone: "세련되고 감각적인 카페 에세이 어조",
  },
  {
    id: "busan-gwanganri-food",
    title: "부산 광안리 오션뷰 브런치 & 자갈치 싱싱 해산물 미식 코스",
    categoryType: "food",
    destination: "부산 광안리 & 남포동 맛집 투어",
    style: "오션뷰 브런치, 싱싱한 제철 활어회, 로컬 미식",
    icon: "🍣",
    description: "광안대교가 한눈에 보이는 테라스 브런치 카페부터 자갈치 시장 활어회와 칼칼한 해물탕까지 바다를 만끽하는 부산 먹방 여행",
    duration: "1박 2일 식도락",
    keywords: ["광안리브런치", "부산해산물", "오션뷰카페", "자갈치시장", "부산먹방"],
    tone: "활기차고 꼼꼼한 먹방 가이드체",
  },

  // --- 🔥 트렌드 / 핫이슈 템플릿 ---
  {
    id: "running-crew-trend",
    title: "요즘 2030 대세 라이프스타일! 한강 야간 러닝 크루 & 플로깅 입문기",
    categoryType: "trend",
    destination: "한강 야간 러닝 크루 & 플로깅",
    style: "러닝 크루, 나이트런, 플로깅, 오운완 루틴",
    icon: "🏃‍♂️",
    description: "인스타에서 핫한 야간 한강 러닝 크루 참여 방법, 입문자 추천 페이스와 러닝화 장비 추천, 환경도 챙기는 플로깅 문화 총정리",
    duration: "퇴근 후 2시간 루틴",
    keywords: ["러닝크루", "한강러닝", "야간달리기", "오운완", "러닝화추천"],
    tone: "동기부여 가득한 트렌디 웰니스 어조",
  },
  {
    id: "dopamine-detox",
    title: "주말 도파민 디톡스! 스마트폰 끄고 떠나는 숲멍 & 북스테이 힐링",
    categoryType: "trend",
    destination: "주말 도파민 디톡스 & 숲속 북스테이",
    style: "도파민 디톡스, 숲멍 힐링, 아날로그 휴식, 북스테이",
    icon: "🌲",
    description: "알림 지옥에서 벗어나 활자 읽기와 숲소리에 집중하는 법, 수도권 인근 감성 북스테이 명소와 24시간 언플러그드 루틴",
    duration: "1박 2일 주말 힐링",
    keywords: ["도파민디톡스", "북스테이", "디지털디톡스", "숲멍힐링", "언플러그드"],
    tone: "차분하고 고요한 힐링 에세이 어조",
  },
  {
    id: "popup-store-hotissue",
    title: "줄 서서 들어가는 주말 성수·더현대 한정판 팝업스토어 완벽 공략법",
    categoryType: "trend",
    destination: "성수동·여의도 팝업스토어 성지",
    style: "팝업스토어 투어, 한정판 굿즈, 포토존 공략, 사전예약",
    icon: "🛍️",
    description: "매주 바뀌는 핫한 브랜드 팝업 현장! 네이버/카카오 사전 예약 꿀팁, 현장 웨이팅 노하우 및 인스타 인생샷 건지는 포토존 지도",
    duration: "주말 방문 가이드",
    keywords: ["팝업스토어", "더현대서울", "성수팝업", "한정판굿즈", "오픈런꿀팁"],
    tone: "발빠르고 알찬 트렌드 리포터 어조",
  },
  {
    id: "workation-trend-guide",
    title: "바다 보며 일하고 저녁엔 서핑! 제주·강릉 일주일 워케이션(Workation) 실전 가이드",
    categoryType: "trend",
    destination: "제주·강릉 바닷가 워케이션",
    style: "워케이션, 디지털 노마드, 코워킹 스페이스, 로컬 라이프",
    icon: "💻",
    description: "와이파이 빵빵한 코워킹 라운지 숙소 추천, 업무 몰입도 200% 올리는 시간 관리법, 일 끝나고 즐기는 로컬 맛집과 일몰 산책",
    duration: "일주일 워케이션",
    keywords: ["워케이션", "제주워케이션", "강릉노마드", "코워킹스페이스", "로컬라이프"],
    tone: "자유롭고 실용적인 노마드 워커 어조",
  },
];
