import { TravelTemplate } from "../types";

export const TRAVEL_TEMPLATES: TravelTemplate[] = [
  // --- 여행 템플릿 ---
  {
    id: "jeju-3days",
    title: "제주도 3박 4일 감성 카페 & 해안도로 코스",
    categoryType: "travel",
    destination: "제주도",
    style: "감성 카페, 해안도로 드라이브, 바다 전망 맛집",
    icon: "🏝️",
    description: "애월 해안도로부터 구좌읍 세화 해변, 우도까지 에메랄드빛 바다와 신상 감성 카페를 정복하는 알찬 3박 4일",
    duration: "3박 4일",
    keywords: ["애월해안도로", "세화해변", "우도자전거투어", "제주흑돼지", "돌담카페"],
    tone: "친근하고 감성적인 ~해요체 (인스타그램 감성)",
  },
  {
    id: "tokyo-gourmet",
    title: "도쿄 2박 3일 미식 & 쇼핑 핫플 탐방기",
    categoryType: "travel",
    destination: "일본 도쿄",
    style: "식도락, 핫플레이스 쇼핑, 야경 감상",
    icon: "🗼",
    description: "시부야 스카이 전망대, 시부야 하라주쿠 빈티지 숍, 아키하바라, 오모테산도 디저트 카페와 긴자 라멘 투어",
    duration: "2박 3일",
    keywords: ["시부야스카이", "오모테산도카페", "신주쿠야경", "도쿄라멘맛집", "하라주쿠쇼핑"],
    tone: "솔직하고 생생한 리얼 후기 체",
  },
  {
    id: "barcelona-gaudi",
    title: "스페인 바르셀로나 가우디 건축 & 타파스 기행",
    categoryType: "travel",
    destination: "스페인 바르셀로나",
    style: "문화 예술, 건축 탐방, 스페인 와인 & 타파스",
    icon: "🏰",
    description: "사그라다 파밀리아 성당, 구엘 공원, 카사 바트요부터 람블라 거리의 바르셀로네타 해변과 타파스 투어까지",
    duration: "4박 5일",
    keywords: ["사그라다파밀리아", "구엘공원", "람블라거리", "바르셀로네타", "스페인타파스"],
    tone: "정보가 풍부한 유럽 전문가 가이드 어조",
  },
  {
    id: "kyoto-autumn",
    title: "교토 3박 4일 고즈넉한 전통 거리 & 힐링 료칸",
    categoryType: "travel",
    destination: "일본 교토",
    style: "전통 문화, 힐링 료칸, 말차 디저트",
    icon: "🍁",
    description: "청수사(키요미즈데라)와 아라시야마 대나무 숲, 가온 거리의 게이샤 거리, 온천 료칸 가이세키 요리 체험",
    duration: "3박 4일",
    keywords: ["아라시야마", "청수사", "기온거리", "료칸가이세키", "교토말차"],
    tone: "서정적이고 고즈넉한 감성 어조",
  },
  {
    id: "danang-family",
    title: "베트남 다낭&호이안 3박 5일 가성비 휴양 코스",
    categoryType: "travel",
    destination: "베트남 다낭/호이안",
    style: "가족 휴양, 해변 리조트, 야경 등불 거리",
    icon: "🥥",
    description: "미케 비치 해변 리조트, 바나힐 케이블카 & 골든브릿지, 호이안 올드타운 밤거리 등불 투어와 반미/쌀국수 맛집",
    duration: "3박 5일",
    keywords: ["미케비치", "바나힐골든브릿지", "호이안올드타운", "다낭야시장", "베트남쌀국수"],
    tone: "친절하고 가족 여행자용 세심한 가이드",
  },
  {
    id: "paris-romantic",
    title: "프랑스 파리 5박 6일 감성 스냅 & 루브르 박물관 코스",
    categoryType: "travel",
    destination: "프랑스 파리",
    style: "에펠탑 야경, 미술관 투어, 센강 크루즈, 베이커리 맛집",
    icon: "🥐",
    description: "에펠탑 샤오궁 스냅 스팟, 루브르 & 오르세 미술관, 센강 바토무슈 크루즈, 몽마르트르 언덕과 크루아상 맛집 투어",
    duration: "5박 6일",
    keywords: ["에펠탑야경", "루브르박물관", "센강크루즈", "몽마르트르", "파리크루아상"],
    tone: "로맨틱하고 감성 가득한 유럽 여행 에세이 어조",
  },

  // --- 생활정보 & 팁 템플릿 ---
  {
    id: "ac-electricity-save",
    title: "여름철 에어컨 전기요금 50% 절약하는 실전 꿀팁 7가지",
    categoryType: "life_info",
    destination: "에어컨 전기세 절약법",
    style: "절약 / 재테크 / 생활노하우",
    icon: "💡",
    description: "인버터형vs정속형 구분법부터 제습 모드의 오해, 서큘레이터 조합 및 에어컨 필터 청소 주기로 전기요금 폭탄 완벽 방지!",
    duration: "소요시간 5분 읽기",
    keywords: ["에어컨전기세절약", "누진세예방", "살림꿀팁", "자취생전기세", "에어컨필터청소"],
    tone: "친근하고 쉬운 생활전문가 블로그체",
  },
  {
    id: "fridge-organization",
    title: "자취생 필수! 10분 만에 끝내는 냉장고 정돈 & 냄새 제거 살림법",
    categoryType: "life_info",
    destination: "냉장고 정돈 및 냄새 제거",
    style: "청소 / 살림 / 자취가이드",
    icon: "🧹",
    description: "소주와 베이킹소다를 활용한 천연 탈취제 만들기, 식재료 보관 기한표, 서랍별 냉장/냉동 보관 법칙 총정리",
    duration: "실행 10분 완료",
    keywords: ["냉장고냄새제거", "자취생살림팁", "베이킹소다활용법", "냉장고정리", "식재료보관법"],
    tone: "위트있고 상쾌한 살림고수 리뷰체",
  },
  {
    id: "one-pan-pasta",
    title: "요알못도 성공하는 15분 초간단 원팬 알리오 올리오 파스타",
    categoryType: "life_info",
    destination: "초간단 원팬 파스타 레시피",
    style: "요리 / 레시피 / 자취 요리",
    icon: "🍳",
    description: "설거지거리 단 1개! 마늘과 올리브유, 페페론치노만으로 파스타 전문점 맛을 내는 황금 비율 원팬 요리 레시피",
    duration: "조리시간 15분",
    keywords: ["원팬파스타", "초간단자취요리", "알리오올리오", "10분레시피", "자취생저녁"],
    tone: "친절하고 친근한 집밥 요리 블로그체",
  },
  {
    id: "phone-battery-tips",
    title: "스마트폰 배터리 수명 2배 늘리고 빠르고 쾌적하게 쓰는 필수 설정",
    categoryType: "life_info",
    destination: "스마트폰 배터리 및 속도 설정",
    style: "디지털 / IT / 스마트폰 팁",
    icon: "📱",
    description: "아이폰 & 갤럭시 배터리 성능 저하 방지 모드, 백그라운드 앱 정리, 다크모드 설정으로 배터리 조기 방전 방지법",
    duration: "설정 3분 완료",
    keywords: ["스마트폰배터리절약", "아이폰꿀팁", "갤러시배터리", "IT테크팁", "스마트폰수명"],
    tone: "명확하고 전문적인 디바이스 가이드체",
  },
  {
    id: "youth-subsidy-2026",
    title: "2026년 청년 & 무주택 서민 필수 정부 지원금 신청 총정리",
    categoryType: "life_info",
    destination: "정부 지원금 및 정책 혜택",
    style: "정책 / 행정 / 서민지원",
    icon: "📑",
    description: "청년도약계좌, 청년 월세 지원금, 대중교통 K-패스 환급 제도 자격 요건과 복지로 사이트 신청 방법 step-by-step",
    duration: "신청 10분 완료",
    keywords: ["청년지원금", "정부혜택", "청년도약계좌", "K패스환급", "복지로신청"],
    tone: "상세하고 알기 쉬운 정보 전달 가이드체",
  },
];
